### ISSUE TITLE
Modifier order is not send to a message ?

### ISSUE THREAD

**Issue by cobra91** [sholafalana/MT5-MT4-Telegram-API-Bot#3]
Hello,
I test your work but i don't see anywhere when a signal is modified.
Did you support it or not ?

**Comment by sholafalana** [comment]
Can you share a screenshot of which trade operation is not working?

**Comment by cobra91** [comment]
It is not that this does not work but rather that there is nothing to indicate the presence of modification of a TP or SL in your code

**Comment by sholafalana** [comment]
![photo_2021-01-08_16-08-15](https://user-images.githubusercontent.com/32399318/104030530-d47b6680-51cb-11eb-919f-9a45241023c0.jpg)
Try it again, i just a check here

**Comment by sholafalana** [comment]
Try it again, I just made a check here

**Comment by sholafalana** [comment]
![Untitledghup](https://user-images.githubusercontent.com/32399318/104030970-74d18b00-51cc-11eb-9b55-2a9475216ce5.png)
