### ISSUE TITLE
Cannot fid mq5 source file

### ISSUE THREAD

**Issue by rahuldhangar** [sholafalana/MT5-MT4-Telegram-API-Bot#4]
First of all, kudos to your efforts here!
I can't seem to find mq5 file in the MQL5 folder so please can you provide the source code along with the executable file for MT5?

**Comment by sholafalana** [comment]
Thanks, It is only the ex5 file available here for the MT5 version, if you are interested in the source code, Contact me on sholafalana777@gmail.com
